package com.dailycodebuffer.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "stock")
public class Company {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String companyCode;

    @DynamoDBAttribute
    private String companyName;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String ceo;
    
    @DynamoDBAttribute
    private String turnover;

    @DynamoDBAttribute
    private String website;

    @DynamoDBAttribute
    private String stockExchange;

    @DynamoDBAttribute
    private String currentStockPrice;
}
